// editor/server.mjs — the 工坊编辑器 (workshop editor): a STANDALONE, optional server (docs/EDITOR.md).
//
// Distribution model (the user's requirement): the editor is NOT part of the game client. It lives in `editor/`, which
// is outside `public/` — and server/index.js only mounts /data/, /shared/, /sim/ and public/ at / — so the game server
// structurally cannot serve a single byte of it. There is no build step, no import from the client, and no feature flag
// in the game. You distribute it by shipping this directory and running:
//
//     node tools/workshop-editor.mjs            # binds 127.0.0.1 by default
//
// It writes only two kinds of file: the packs under `workshop/`, and the support pool `data/support.json` (a
// hand-maintained server config — NOT a build-data output; data/*.json generated by tools/build-data.mjs is never
// touched). It reuses shared/chessAuthoring.js, so the editor, the CLIs and an AI all see the same rules.
//
// Source of truth inside a pack: `<pack>/specs/<slug>.json` is the editable authoring spec; `<pack>/chess.json` is the
// GENERATED artifact the game reads (the same "don't hand-edit the output" stance the project takes for data/*.json).
// A record with no matching spec is preserved untouched, so packs written by tools/workshop-scaffold.mjs or by hand are
// never destroyed by the editor.

import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { deriveChessRecord, validateChessRecord, chessIds, formatIssues, authoringErrors } from '../shared/chessAuthoring.js';
import { TILE_PALETTE, DEPLOY_RECTS, STAGE_ROWS, STAGE_COLS, stageErrors } from '../shared/stageAuthoring.js';
import { deriveStage, validateStageRecord } from '../server/stageAuthoring.js';
import {
  deriveEnemy, validateEnemy, enemyErrors, enemyKey as enemyKeyOf, ENEMY_RANKS, ENEMY_MOTIONS, ENEMY_DMG_TYPES, ENEMY_APPLY_WAYS,
  ENEMY_AC_TYPES, ENEMY_IMMUNITIES, ENEMY_STAT_DEFAULTS,
} from '../shared/enemyAuthoring.js';
import {
  deriveWave, validateWave, waveErrors, waveId as waveIdOf, waveSummaryLine,
  WAVE_KINDS, SPAWN_SLOTS, SPAWN_FIELDS, ROUNDS_PER_MODE,
} from '../shared/waveAuthoring.js';
import { normalizeSupportConfig } from '../shared/support.js';
import {
  deriveItem, validateItem, itemErrors, itemIds as itemIdsOf, itemSummaryLine,
  ITEM_TYPES, ITEM_CATEGORIES, COUNT_TYPES, ITEM_DURATIONS, UPGRADE_NUMS,
} from '../shared/itemAuthoring.js';
import { loadWorkshop, WORKSHOP_DIR } from '../server/workshop.js';
import { withForgeMeta } from '../shared/forgeNotice.js';

export const EDITOR_ROOT = path.dirname(fileURLToPath(import.meta.url));
export const UI_DIR = path.join(EDITOR_ROOT, 'ui');
const REPO_ROOT = path.resolve(EDITOR_ROOT, '..');
export const DATA_DIR = path.join(REPO_ROOT, 'data');
export const SUPPORT_FILE = path.join(DATA_DIR, 'support.json');

const PACK_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/;
const SLUG_RE = /^[a-z0-9][a-z0-9_]{0,31}$/;
const BODY_LIMIT = 1 << 20; // 1 MB is far beyond any spec
const quietLog = { info() {}, warn() {}, error() {}, debug() {} };
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml' };

/** What the 3D preview may pull from `public/` (modules and their data) — never an arbitrary client file. */
const CLIENT_PREVIEW_TYPES = new Set(['.js', '.mjs', '.json', '.css']);
/** …and from `public/assets/`: the board art the local-client manifest points at. */
const ART_TYPES = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.json', '.obj', '.bin', '.atlas', '.skel']);
const ART_MIME = new Map([
  ['.png', 'image/png'], ['.jpg', 'image/jpeg'], ['.jpeg', 'image/jpeg'], ['.webp', 'image/webp'], ['.gif', 'image/gif'],
  ['.json', 'application/json; charset=utf-8'], ['.obj', 'text/plain; charset=utf-8'], ['.bin', 'application/octet-stream'],
  ['.js', 'text/javascript; charset=utf-8'], ['.mjs', 'text/javascript; charset=utf-8'], ['.css', 'text/css; charset=utf-8'],
]);

const readJson = (p, fallback = null) => {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; }
};
const writeJson = async (p, obj) => {
  await fsp.mkdir(path.dirname(p), { recursive: true });
  await fsp.writeFile(p, `${JSON.stringify(obj, null, 2)}\n`);
};

/** Official chess, reduced to what the editor needs (the spine picker: the repo ships no assets). */
function officialChess(dataDir) {
  const data = readJson(path.join(dataDir, 'chess.json'), {}) || {};
  const out = [];
  for (const [id, rec] of Object.entries(data)) {
    if (!rec || rec.isGolden || !rec.visible || rec.isHidden || rec.isDiy) continue;
    out.push({ id, name: rec.name, tier: rec.tier, profession: rec.profession, subProfessionId: rec.subProfessionId, position: rec.position, spine: rec.assets?.spine ?? null });
  }
  return out.sort((a, b) => (a.tier - b.tier) || a.id.localeCompare(b.id));
}

/** id → tier for every chess id the server can see: the official data plus every pack's chess.json (support toggle). */
function chessTierLookup(root, dataDir) {
  /** @type {Map<string, number>} */
  const out = new Map();
  const official = readJson(path.join(dataDir, 'chess.json'), {}) || {};
  for (const [id, rec] of Object.entries(official)) if (Number.isInteger(rec && rec.tier)) out.set(id, rec.tier);
  for (const dir of fs.existsSync(root) ? fs.readdirSync(root) : []) {
    if (!PACK_ID_RE.test(dir)) continue;
    const recs = readJson(path.join(root, dir, 'chess.json'), {}) || {};
    for (const [id, rec] of Object.entries(recs)) if (Number.isInteger(rec && rec.tier)) out.set(id, rec.tier);
  }
  return out;
}

// ---- 地图 (stages) ---------------------------------------------------------------------------------
//
// Same file model as operators: `<pack>/stage-specs/<id>.json` is the editable SOURCE (what the placer writes), and
// `<pack>/stages.json` is the GENERATED artifact the game reads. A record with no spec is preserved untouched, so a
// pack authored by the CLI or by hand is never destroyed — and a spec that fails to derive owns nothing, so a broken
// sibling can never silently delete another map's records.

const STAGE_SPEC_DIR = 'stage-specs';
const STAGE_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_\-.:]{0,63}$/;

/** The in-scope modes a stage may be assigned to (`config.modes[m].inScope !== false`). */
function inScopeModes(dataDir) {
  const cfg = readJson(path.join(dataDir, 'config.json'), null);
  const modes = cfg && cfg.modes && typeof cfg.modes === 'object' ? cfg.modes : {};
  return Object.entries(modes)
    .filter(([, m]) => m && m.inScope !== false && typeof m.modeId === 'string')
    .map(([, m]) => ({ id: m.modeId, name: m.name || m.modeId, difficulty: m.difficulty || null }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** A pack's stage specs, in a stable order. */
function packStageSpecs(packDir) {
  const out = [];
  const dir = path.join(packDir, STAGE_SPEC_DIR);
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    const spec = readJson(path.join(dir, name), null);
    if (spec) out.push(spec);
  }
  return out;
}

/** Write a pack's `stages.json` from its stage specs, preserving every record no spec owns. */
function regenerateStages(packDir, officialStages, dropIds = []) {
  const existing = readJson(path.join(packDir, 'stages.json'), {}) || {};
  const owned = new Set(Array.isArray(dropIds) ? dropIds : []);
  const fresh = {};
  const errors = [];
  for (const spec of packStageSpecs(packDir)) {
    const derived = deriveStage(spec);
    if (!derived.ok) {
      // a spec that cannot derive owns nothing: claiming its id here would delete the previous record on an unrelated save
      errors.push({ id: spec && spec.id, issues: derived.errors.map((e) => ({ ...e, severity: 'error' })) });
      continue;
    }
    owned.add(derived.stage.id);
    const issues = stageErrors(validateStageRecord(derived.stage, { id: derived.stage.id, officialIds: officialStages }));
    if (issues.length) errors.push({ id: derived.stage.id, issues });
    fresh[derived.stage.id] = derived.stage;
  }
  const records = {};
  for (const [id, rec] of Object.entries(existing)) if (!owned.has(id)) records[id] = rec;
  Object.assign(records, fresh);
  return { records, generated: Object.keys(fresh), errors };
}

// ---- 怪物 (enemies) --------------------------------------------------------------------------------
//
// Same file model again: `<pack>/enemy-specs/<key>.json` is the editable SOURCE (what the form writes) and
// `<pack>/enemies.json` is the GENERATED artifact. `attrPower` and `be` are DERIVED from the stats on every save — a
// hand-typed value would swap the wrong number of enemies in a faction replacement, silently.

const ENEMY_SPEC_DIR = 'enemy-specs';

/** A pack's enemy specs, in a stable order. */
function packEnemySpecs(packDir) {
  const out = [];
  const dir = path.join(packDir, ENEMY_SPEC_DIR);
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    const spec = readJson(path.join(dir, name), null);
    if (spec) out.push(spec);
  }
  return out;
}

/** Write a pack's `enemies.json` from its enemy specs, preserving every record no spec owns. */
function regenerateEnemies(packDir, officialEnemies, dropIds = []) {
  const existing = readJson(path.join(packDir, 'enemies.json'), {}) || {};
  const owned = new Set(Array.isArray(dropIds) ? dropIds : []);
  const fresh = {};
  const errors = [];
  for (const spec of packEnemySpecs(packDir)) {
    const derived = deriveEnemy(spec);
    if (!derived.ok) {
      // a spec that cannot derive owns nothing: claiming its key would delete the previous record on an unrelated save
      errors.push({ key: spec && spec.id, issues: derived.errors.map((e) => ({ ...e, severity: 'error' })) });
      continue;
    }
    owned.add(derived.enemy.key);
    const issues = enemyErrors(validateEnemy(derived.enemy, { key: derived.enemy.key, officialIds: officialEnemies }));
    if (issues.length) errors.push({ key: derived.enemy.key, issues });
    fresh[derived.enemy.key] = derived.enemy;
  }
  const records = {};
  for (const [key, rec] of Object.entries(existing)) if (!owned.has(key)) records[key] = rec;
  Object.assign(records, fresh);
  return { records, generated: Object.keys(fresh), errors };
}

/** The enum vocabularies the monster form renders, so the UI never invents one. */
const ENEMY_VOCAB = () => ({
  ranks: [...ENEMY_RANKS], motions: [...ENEMY_MOTIONS], dmgTypes: [...ENEMY_DMG_TYPES], applyWays: [...ENEMY_APPLY_WAYS],
  acTypes: [...ENEMY_AC_TYPES], immunities: [...ENEMY_IMMUNITIES], statDefaults: { ...ENEMY_STAT_DEFAULTS },
});

// ---- 出怪 (waves) ----------------------------------------------------------------------------------
//
// Same file model a third time: `<pack>/wave-specs/<id>.json` is the editable SOURCE (what the timeline writes) and
// `<pack>/waves.json` is the GENERATED artifact. `totalCount` and `slotCounts` are DERIVED from the spawns on every
// save, with build-data's exact asymmetry (slotCounts counts `unharmful` spawns, totalCount does not).
//
// A wave's ROUTES are the map paths it walks. The timeline shows them over the map the wave runs on, and validation
// checks that every spawn's `routeIndex` addresses one of them — the sim silently falls back to route 0 otherwise.

const WAVE_SPEC_DIR = 'wave-specs';

/** A pack's wave specs, in a stable order. */
function packWaveSpecs(packDir) {
  const out = [];
  const dir = path.join(packDir, WAVE_SPEC_DIR);
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    const spec = readJson(path.join(dir, name), null);
    if (spec) out.push(spec);
  }
  return out;
}

/** Write a pack's `waves.json` from its wave specs, preserving every record no spec owns. */
function regenerateWaves(packDir, officialWaves, knownEnemyKeys, dropIds = []) {
  const existing = readJson(path.join(packDir, 'waves.json'), {}) || {};
  const owned = new Set(Array.isArray(dropIds) ? dropIds : []);
  const fresh = {};
  const errors = [];
  for (const spec of packWaveSpecs(packDir)) {
    const derived = deriveWave(spec);
    if (!derived.ok) {
      // a spec that cannot derive owns nothing: claiming its id would delete the previous record on an unrelated save
      errors.push({ id: spec && spec.id, issues: derived.errors.map((e) => ({ ...e, severity: 'error' })) });
      continue;
    }
    owned.add(derived.wave.id);
    const issues = waveErrors(validateWave(derived.wave, { id: derived.wave.id, officialIds: officialWaves, knownEnemyKeys }));
    if (issues.length) errors.push({ id: derived.wave.id, issues });
    fresh[derived.wave.id] = derived.wave;
  }
  const records = {};
  for (const [id, rec] of Object.entries(existing)) if (!owned.has(id)) records[id] = rec;
  Object.assign(records, fresh);
  return { records, generated: Object.keys(fresh), errors };
}

// ---- 装备 (items) ----------------------------------------------------------------------------------
//
// The same file model a fourth time: `<pack>/item-specs/<slug>.json` is the editable SOURCE (what the form writes) and
// `<pack>/items.json` is the GENERATED artifact. An item is AUTHORED AS A PAIR: one spec derives the normal record and
// its golden twin, because `mergeable` is meaningless without a twin to merge into. `params` is re-derived from the
// buffs on every save — the engine reads `params`, so a stale one is an item whose card lies about what it does.

const ITEM_SPEC_DIR = 'item-specs';

/** A pack's item specs, in a stable order. */
function packItemSpecs(packDir) {
  const out = [];
  const dir = path.join(packDir, ITEM_SPEC_DIR);
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    const spec = readJson(path.join(dir, name), null);
    if (spec) out.push(spec);
  }
  return out;
}

/** Write a pack's `items.json` from its item specs, preserving every record no spec owns. */
function regenerateItems(packDir, officialItems, dropIds = []) {
  const existing = readJson(path.join(packDir, 'items.json'), {}) || {};
  const owned = new Set(Array.isArray(dropIds) ? dropIds : []);
  const fresh = {};
  const errors = [];
  for (const spec of packItemSpecs(packDir)) {
    const derived = deriveItem(spec);
    if (!derived.ok) {
      // a spec that cannot derive owns nothing: claiming its ids would delete the previous records on an unrelated save
      errors.push({ id: spec && spec.id, issues: derived.errors.map((e) => ({ ...e, severity: 'error' })) });
      continue;
    }
    for (const rec of [derived.base, derived.golden].filter(Boolean)) {
      owned.add(rec.id);
      const issues = itemErrors(validateItem(rec, { id: rec.id, officialIds: officialItems }));
      if (issues.length) errors.push({ id: rec.id, issues });
      fresh[rec.id] = rec;
    }
  }
  const records = {};
  for (const [id, rec] of Object.entries(existing)) if (!owned.has(id)) records[id] = rec;
  Object.assign(records, fresh);
  return { records, generated: Object.keys(fresh), errors };
}

/**
 * The author name an Option's `_meta` records: the editor's `forgeAuthor` option (or `SP_FORGE_AUTHOR`), else the pack's
 * own `pack.json` author, else null — and the stamp then says "未署名 (anonymous)" rather than inventing a name.
 */
function authorFor(packDir, explicit = null) {
  if (typeof explicit === 'string' && explicit.trim()) return explicit.trim();
  const manifest = readJson(path.join(packDir, 'pack.json'), null);
  const author = manifest && typeof manifest.author === 'string' ? manifest.author.trim() : '';
  return author || null;
}

/**
 * The `trapId` values an item may reuse. A workshop pack ships no art, so borrowing an existing equip icon is the only
 * way an item gets a real picture — exactly like an enemy borrowing a `spine`. Deduplicated, because many items share
 * one trap id, and labelled with the item it came from so the picker reads as names rather than keys.
 */
function itemIconChoices(dataDir) {
  const byTrap = new Map();
  for (const [id, rec] of Object.entries(readJson(path.join(dataDir, 'items.json'), {}) || {})) {
    if (!rec || rec.isGolden || !rec.trapId || byTrap.has(rec.trapId)) continue;
    byTrap.set(rec.trapId, { trapId: rec.trapId, from: id, name: rec.name ?? id });
  }
  return [...byTrap.values()].sort((a, b) => a.trapId.localeCompare(b.trapId));
}

/** The enemy keys a wave may spawn: the merged official set plus every pack's own monsters. */
function knownEnemyKeysFor(root, dataDir) {
  const keys = new Set(Object.keys(readJson(path.join(dataDir, 'enemies.json'), {}) || {}));
  if (!root || !fs.existsSync(root)) return keys;
  for (const packId of fs.readdirSync(root)) {
    if (!PACK_ID_RE.test(packId)) continue;
    for (const key of Object.keys(readJson(path.join(root, packId, 'enemies.json'), {}) || {})) keys.add(key);
  }
  return keys;
}

/**
 * The maps a wave can be shown over: the official ones (id + name + their S/E tiles for the route preview) and the
 * packs' own stages, whose `rounds`/`bossRounds` are what actually bind a wave to a round (server/match/waves.js).
 */
function stageChoices(root, dataDir) {
  const out = [];
  for (const [id, rec] of Object.entries(readJson(path.join(dataDir, 'stages.json'), {}) || {})) {
    out.push({ id, name: rec.name ?? id, official: true, rounds: rec.rounds ?? null });
  }
  if (root && fs.existsSync(root)) {
    for (const packId of fs.readdirSync(root)) {
      if (!PACK_ID_RE.test(packId)) continue;
      for (const [id, rec] of Object.entries(readJson(path.join(root, packId, 'stages.json'), {}) || {})) {
        out.push({ id, name: rec.name ?? id, pack: packId, official: false, rounds: rec.rounds ?? null, bossRounds: rec.bossRounds ?? null });
      }
    }
  }
  return out;
}

/** Everything the UI renders for one pack: its specs (editable) plus every record and its issues. */
function packState(root, packId, officialIds) {
  const packDir = path.join(root, packId);
  const manifest = readJson(path.join(packDir, 'pack.json'), null);
  const records = readJson(path.join(packDir, 'chess.json'), {}) || {};
  const specDir = path.join(packDir, 'specs');
  const specs = [];
  if (fs.existsSync(specDir)) {
    for (const name of fs.readdirSync(specDir).sort()) {
      if (!name.endsWith('.json')) continue;
      const spec = readJson(path.join(specDir, name), null);
      if (spec) specs.push(spec);
    }
  }
  const generated = new Set();
  for (const spec of specs) {
    const ids = chessIds(spec.id);
    if (ids) { generated.add(ids.base); generated.add(ids.golden); }
  }
  const operators = [];
  for (const [id, rec] of Object.entries(records)) {
    const issues = validateChessRecord(rec, { id, officialIds });
    operators.push({
      chessId: id, name: rec.name ?? null, tier: rec.tier ?? null, isGolden: !!rec.isGolden,
      profession: rec.profession ?? null, position: rec.position ?? null,
      managed: generated.has(id), // a spec owns it → the editor regenerates it
      issues,
    });
  }
  return { id: packId, manifest, specs, operators, dir: packDir };
}

/**
 * Write one pack's `chess.json` from its specs, PRESERVING every record no spec owns.
 * `dropIds` removes records explicitly — needed when a spec was just deleted, because ownership can no longer be
 * derived from the (now absent) spec.
 * @returns {{ records: object, generated: string[] }}
 */
function regeneratePack(root, packId, officialIds, dropIds = []) {
  const packDir = path.join(root, packId);
  const existing = readJson(path.join(packDir, 'chess.json'), {}) || {};
  const specDir = path.join(packDir, 'specs');
  const owned = new Set(Array.isArray(dropIds) ? dropIds : []);
  const fresh = {};
  const errors = [];
  if (fs.existsSync(specDir)) {
    for (const name of fs.readdirSync(specDir).sort()) {
      if (!name.endsWith('.json')) continue;
      const spec = readJson(path.join(specDir, name), null);
      if (!spec) continue;
      const derived = deriveChessRecord(spec);
      if (!derived.ok) {
        // A spec that cannot derive OWNS NOTHING: its previous records must be preserved. Claiming them here and then
        // skipping would delete them from chess.json on an unrelated save — data loss behind a 200 OK.
        errors.push({ slug: spec.id, issues: derived.errors.map((e) => ({ ...e, severity: 'error' })) });
        continue;
      }
      const ids = chessIds(spec.id);
      if (ids) { owned.add(ids.base); owned.add(ids.golden); }
      for (const [id, rec] of [[derived.base.chessId, derived.base], [derived.golden.chessId, derived.golden]]) {
        const issues = authoringErrors(validateChessRecord(rec, { id, officialIds }));
        if (issues.length) errors.push({ slug: spec.id, issues });
        fresh[id] = rec;
      }
    }
  }
  const records = {};
  for (const [id, rec] of Object.entries(existing)) if (!owned.has(id)) records[id] = rec; // hand-written / CLI records survive
  Object.assign(records, fresh);
  return { records, generated: Object.keys(fresh), errors };
}

/** Point data/support.json's pool at a record: the "是否助战" switch of the editor. */
async function toggleSupport(supportFile, chessId, tier, enabled) {
  const raw = readJson(supportFile, null);
  if (!raw || typeof raw !== 'object') throw Object.assign(new Error('data/support.json is missing or unreadable'), { status: 500 });
  if (!Number.isInteger(tier) || tier < 1 || tier > 6) throw Object.assign(new Error('tier must be 1..6'), { status: 400 });
  raw.pool = raw.pool && typeof raw.pool === 'object' ? raw.pool : {};
  const list = Array.isArray(raw.pool[tier]) ? raw.pool[tier] : (raw.pool[tier] = []);
  const at = list.indexOf(chessId);
  if (enabled && at < 0) list.push(chessId);
  if (!enabled && at >= 0) list.splice(at, 1);
  list.sort();
  await writeJson(supportFile, raw);
  return normalizeSupportConfig(raw);
}

async function readBody(req) {
  const chunks = [];
  let size = 0;
  for await (const c of req) {
    size += c.length;
    if (size > BODY_LIMIT) throw Object.assign(new Error('request body too large'), { status: 413 });
    chunks.push(c);
  }
  if (!chunks.length) return {};
  try {
    return JSON.parse(Buffer.concat(chunks).toString('utf8'));
  } catch {
    throw Object.assign(new Error('request body is not valid JSON'), { status: 400 });
  }
}

const sendJson = (res, status, obj) => {
  const body = Buffer.from(JSON.stringify(obj), 'utf8');
  res.writeHead(status, { 'Content-Type': MIME['.json'], 'Content-Length': body.length, 'Cache-Control': 'no-store' });
  res.end(body);
};

/**
 * Create the editor's HTTP server. Exported for tests (`port: 0`).
 * @param {{ workshopRoot?: string, host?: string, port?: number, dataDir?: string, supportFile?: string, log?: object }} [opts]
 */
export async function createEditorServer(opts = {}) {
  const root = path.resolve(opts.workshopRoot ?? WORKSHOP_DIR);
  // The data dir and the support file are injectable so a test never rewrites the real data/support.json.
  const dataDir = path.resolve(opts.dataDir ?? DATA_DIR);
  const supportFile = path.resolve(opts.supportFile ?? path.join(dataDir, 'support.json'));
  const log = opts.log ?? quietLog;
  const officialIds = new Set(Object.keys(readJson(path.join(dataDir, 'chess.json'), {}) || {}));
  const officialStages = new Set(Object.keys(readJson(path.join(dataDir, 'stages.json'), {}) || {}));
  const officialEnemies = new Set(Object.keys(readJson(path.join(dataDir, 'enemies.json'), {}) || {}));
  const officialWaves = new Set(Object.keys(readJson(path.join(dataDir, 'waves.json'), {}) || {}));
  const officialItems = new Set(Object.keys(readJson(path.join(dataDir, 'items.json'), {}) || {}));
  // The name stamped into every Option's `_meta` (shared/forgeNotice.js): the explicit option first, then the
  // environment, then the pack's own `pack.json` author — resolved per save by `authorFor` below.
  const forgeAuthor = typeof opts.forgeAuthor === 'string' && opts.forgeAuthor.trim()
    ? opts.forgeAuthor.trim()
    : (typeof process.env.SP_FORGE_AUTHOR === 'string' && process.env.SP_FORGE_AUTHOR.trim() ? process.env.SP_FORGE_AUTHOR.trim() : null);
  const official = officialChess(dataDir);

  const server = http.createServer((req, res) => {
    handle(req, res).catch((e) => {
      const status = e && e.status ? e.status : 500;
      if (status >= 500) log.error?.('[editor] request failed', e);
      sendJson(res, status, { error: e.message });
    });
  });

  async function handle(req, res) {
    const url = new URL(req.url || '/', 'http://localhost');
    const p = url.pathname;
    const method = req.method || 'GET';

    // ---- API ---------------------------------------------------------------------------------------
    if (p === '/api/state' && method === 'GET') {
      const loaded = loadWorkshop(root, { log: quietLog });
      const packs = [];
      for (const dir of fs.existsSync(root) ? fs.readdirSync(root).sort() : []) {
        if (!PACK_ID_RE.test(dir) || !fs.existsSync(path.join(root, dir, 'pack.json'))) continue;
        packs.push(packState(root, dir, officialIds));
      }
      return sendJson(res, 200, {
        workshopRoot: root,
        packs,
        loadErrors: loaded.errors,
        support: normalizeSupportConfig(readJson(supportFile, null)),
        officialChess: official,
        officialCount: officialIds.size,
      });
    }

    // derive + validate WITHOUT writing: the live preview of the form
    if (p === '/api/preview' && method === 'POST') {
      const { spec } = await readBody(req);
      const derived = deriveChessRecord(spec);
      if (!derived.ok) return sendJson(res, 200, { ok: false, errors: derived.errors, warnings: [] });
      const issues = [];
      for (const [id, rec] of [[derived.base.chessId, derived.base], [derived.golden.chessId, derived.golden]]) {
        issues.push(...validateChessRecord(rec, { id, officialIds }));
      }
      return sendJson(res, 200, {
        ok: authoringErrors(issues).length === 0,
        errors: issues.filter((i) => i.severity === 'error'),
        warnings: [...derived.warnings, ...issues.filter((i) => i.severity === 'warning').map((i) => i.message)],
        base: derived.base, golden: derived.golden,
      });
    }

    // create/update one operator: spec → specs/<slug>.json, then regenerate chess.json
    if (p.startsWith('/api/packs/') && p.endsWith('/operators') && method === 'POST') {
      const packId = p.slice('/api/packs/'.length, -'/operators'.length);
      if (!PACK_ID_RE.test(packId)) throw Object.assign(new Error('bad pack id'), { status: 400 });
      const { spec } = await readBody(req);
      const derived = deriveChessRecord(spec);
      if (!derived.ok) return sendJson(res, 400, { error: 'the spec is invalid', errors: derived.errors });
      const ids = chessIds(spec.id);
      if (!SLUG_RE.test(ids.slug)) throw Object.assign(new Error('bad operator id'), { status: 400 });
      const errs = [...validateChessRecord(derived.base, { id: derived.base.chessId, officialIds }), ...validateChessRecord(derived.golden, { id: derived.golden.chessId, officialIds })];
      const blocking = authoringErrors(errs);
      if (blocking.length) return sendJson(res, 400, { error: 'the operator did not validate', errors: blocking });

      const packDir = path.join(root, packId);
      const manifestPath = path.join(packDir, 'pack.json');
      if (!fs.existsSync(manifestPath)) {
        await writeJson(manifestPath, {
          id: packId, name: spec.name || packId, version: '0.1.0', author: authorFor(packDir, forgeAuthor), license: null,
          description: null, gameVersion: '0.1.3', content: ['chess'], overrides: [],
        });
      }
      const specPath = path.join(packDir, 'specs', `${ids.slug}.json`);
      const previousSpec = readJson(specPath, null);
      await writeJson(specPath, withForgeMeta(spec, { author: authorFor(packDir, forgeAuthor), packId, now: new Date().toISOString(), previous: previousSpec }));
      const regen = regeneratePack(root, packId, officialIds);
      if (regen.errors.length) {
        // another spec in this pack no longer derives: report it rather than silently writing a pack that lost records
        return sendJson(res, 400, { error: 'another operator in this pack no longer derives — fix it before saving', errors: regen.errors });
      }
      await writeJson(path.join(packDir, 'chess.json'), regen.records);
      return sendJson(res, 200, { ok: true, slug: ids.slug, generated: regen.generated, warnings: derived.warnings });
    }

    // delete one operator (its spec AND the records it owned)
    if (p.startsWith('/api/packs/') && p.includes('/operators/') && method === 'DELETE') {
      const rest = p.slice('/api/packs/'.length);
      const cut = rest.indexOf('/operators/');
      const packId = rest.slice(0, cut);
      const slug = rest.slice(cut + '/operators/'.length);
      if (!PACK_ID_RE.test(packId) || !SLUG_RE.test(slug)) throw Object.assign(new Error('bad id'), { status: 400 });
      const specPath = path.join(root, packId, 'specs', `${slug}.json`);
      if (fs.existsSync(specPath)) await fsp.rm(specPath);
      // the spec is gone, so ownership cannot be derived any more: name the records it owned explicitly
      const ids = chessIds(slug);
      const regen = regeneratePack(root, packId, officialIds, ids ? [ids.base, ids.golden] : []);
      await writeJson(path.join(root, packId, 'chess.json'), regen.records);
      // a broken sibling spec is reported, not hidden (its records are preserved — see regeneratePack)
      return sendJson(res, 200, { ok: true, removed: slug, generated: regen.generated, errors: regen.errors });
    }

    // 是否助战: add/remove the id in data/support.json's pool for its tier
    if (p === '/api/support/toggle' && method === 'POST') {
      const { chessId, tier, enabled } = await readBody(req);
      if (typeof chessId !== 'string' || !chessId) throw Object.assign(new Error('chessId is required'), { status: 400 });
      // the client supplies the tier: never trust it — the id must exist and the tier must be the record's own, or the
      // pool would take an id that isSupportChess can never accept (junk that looks configured but does nothing)
      const actual = chessTierLookup(root, dataDir).get(chessId);
      if (actual === undefined) throw Object.assign(new Error(`unknown chess id "${chessId}"`), { status: 400 });
      if (actual !== tier) throw Object.assign(new Error(`tier ${tier} does not match the record's tier ${actual}`), { status: 400 });
      const cfg = await toggleSupport(supportFile, chessId, tier, enabled === true);
      return sendJson(res, 200, { ok: true, enabled: enabled === true, support: cfg });
    }

    // ---- 地图 (stages): what the placer needs, and its save path -------------------------------------
    if (p === '/api/stages' && method === 'GET') {
      const stages = [];
      for (const packId of fs.existsSync(root) ? fs.readdirSync(root).sort() : []) {
        if (!PACK_ID_RE.test(packId) || !fs.existsSync(path.join(root, packId, 'pack.json'))) continue;
        const packDir = path.join(root, packId);
        const managed = new Set(packStageSpecs(packDir).map((s) => s.id));
        const records = readJson(path.join(packDir, 'stages.json'), {}) || {};
        for (const [id, rec] of Object.entries(records)) {
          stages.push({
            pack: packId, id, name: rec.name ?? id, managed: managed.has(id),
            weight: rec.weight ?? null,
            modes: Array.isArray(rec.modes) ? rec.modes : [],
            groundPaths: Object.keys(rec.groundPaths || {}).length,
            deployMelee: rec.deployTiles?.normal?.melee?.length ?? 0,
            routes: managed.has(id) ? (packStageSpecs(packDir).find((s) => s.id === id)?.routes ?? []).length : 0,
            issues: validateStageRecord(rec, { id, officialIds: officialStages }),
          });
        }
      }
      return sendJson(res, 200, {
        stages, palette: TILE_PALETTE, rects: DEPLOY_RECTS, size: [STAGE_ROWS, STAGE_COLS],
        officialStages: [...officialStages].sort(),
        modes: inScopeModes(dataDir),
      });
    }

    // derive + validate a map WITHOUT writing: the placer's live feedback while painting
    if (p === '/api/stages/preview' && method === 'POST') {
      const { spec } = await readBody(req);
      const derived = deriveStage(spec);
      if (!derived.ok) return sendJson(res, 200, { ok: false, errors: derived.errors, warnings: [] });
      const issues = validateStageRecord(derived.stage, { id: derived.stage.id, officialIds: officialStages });
      return sendJson(res, 200, {
        ok: stageErrors(issues).length === 0,
        errors: issues.filter((i) => i.severity === 'error'),
        warnings: [...derived.warnings, ...issues.filter((i) => i.severity === 'warning').map((i) => i.message)],
        record: derived.stage,
        // the sim's own walk for each authored route: the placer draws THESE, so the author sees where enemies go
        routePaths: derived.routePaths ?? [],
      });
    }

    if (p.startsWith('/api/packs/') && p.endsWith('/stages') && method === 'POST') {
      const packId = p.slice('/api/packs/'.length, -'/stages'.length);
      if (!PACK_ID_RE.test(packId)) throw Object.assign(new Error('bad pack id'), { status: 400 });
      const { spec } = await readBody(req);
      if (!spec || typeof spec !== 'object' || !STAGE_ID_RE.test(String(spec.id || ''))) {
        throw Object.assign(new Error('spec.id must be a slug (letters, digits, _ - . :)'), { status: 400 });
      }
      const derived = deriveStage(spec);
      if (!derived.ok) return sendJson(res, 400, { error: 'the map spec is invalid', errors: derived.errors });
      const blocking = stageErrors(validateStageRecord(derived.stage, { id: derived.stage.id, officialIds: officialStages }));
      if (blocking.length) return sendJson(res, 400, { error: 'the map did not validate', errors: blocking });

      const packDir = path.join(root, packId);
      const manifestPath = path.join(packDir, 'pack.json');
      const existingManifest = readJson(manifestPath, null);
      const content = new Set(Array.isArray(existingManifest?.content) ? existingManifest.content : []);
      content.add('stages');
      await writeJson(manifestPath, existingManifest
        ? { ...existingManifest, content: [...content].sort() }
        : { id: packId, name: spec.name || packId, version: '0.1.0', author: authorFor(packDir, forgeAuthor), license: null, description: null, gameVersion: '0.1.3', content: [...content], overrides: [] });
      const specPath = path.join(packDir, STAGE_SPEC_DIR, `${derived.stage.id}.json`);
      const previousSpec = readJson(specPath, null);
      await writeJson(specPath, withForgeMeta(spec, { author: authorFor(packDir, forgeAuthor), packId, now: new Date().toISOString(), previous: previousSpec }));
      const regen = regenerateStages(packDir, officialStages);
      if (regen.errors.length) {
        return sendJson(res, 400, { error: 'another map in this pack no longer derives — fix it before saving', errors: regen.errors });
      }
      await writeJson(path.join(packDir, 'stages.json'), regen.records);
      return sendJson(res, 200, { ok: true, id: derived.stage.id, generated: regen.generated, warnings: derived.warnings });
    }

    if (p.startsWith('/api/packs/') && p.includes('/stages/') && method === 'DELETE') {
      const rest = p.slice('/api/packs/'.length);
      const cut = rest.indexOf('/stages/');
      const packId = rest.slice(0, cut);
      const stageId = rest.slice(cut + '/stages/'.length);
      if (!PACK_ID_RE.test(packId) || !STAGE_ID_RE.test(stageId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const specPath = path.join(root, packId, STAGE_SPEC_DIR, `${stageId}.json`);
      if (fs.existsSync(specPath)) await fsp.rm(specPath);
      const regen = regenerateStages(path.join(root, packId), officialStages, [stageId]);
      await writeJson(path.join(root, packId, 'stages.json'), regen.records);
      return sendJson(res, 200, { ok: true, removed: stageId, generated: regen.generated, errors: regen.errors });
    }

    // the stored SPEC the placer edits (the source of truth), plus the generated record for reference
    if (p.startsWith('/api/stages/') && method === 'GET') {
      const rest = p.slice('/api/stages/'.length).split('/');
      if (rest.length !== 2) throw Object.assign(new Error('not found'), { status: 404 });
      const [packId, stageId] = rest;
      if (!PACK_ID_RE.test(packId) || !STAGE_ID_RE.test(stageId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const packDir = path.join(root, packId);
      return sendJson(res, 200, {
        spec: readJson(path.join(packDir, STAGE_SPEC_DIR, `${stageId}.json`), null),
        record: (readJson(path.join(packDir, 'stages.json'), {}) || {})[stageId] ?? null,
      });
    }

    // ---- 怪物 (enemies): the form's data and its save path ------------------------------------------
    if (p === '/api/enemies' && method === 'GET') {
      const enemies = [];
      for (const packId of fs.existsSync(root) ? fs.readdirSync(root).sort() : []) {
        if (!PACK_ID_RE.test(packId) || !fs.existsSync(path.join(root, packId, 'pack.json'))) continue;
        const packDir = path.join(root, packId);
        const managed = new Set(packEnemySpecs(packDir).map((s) => {
          const ids = s && s.id ? enemyKeyOf(s.id) : null;
          return ids ? ids.key : null;
        }).filter(Boolean));
        const records = readJson(path.join(packDir, 'enemies.json'), {}) || {};
        for (const [key, rec] of Object.entries(records)) {
          enemies.push({
            pack: packId, key, name: rec.name ?? key, rank: rec.rank ?? null, applyWay: rec.applyWay ?? null,
            motion: rec.stats?.motion ?? null, dmgType: rec.stats?.dmgType ?? null,
            isFlyEnemy: rec.isFlyEnemy === true, tokenOnly: rec.tokenOnly === true,
            attrPower: rec.attrPower ?? null, be: rec.be ?? null,
            abilities: Array.isArray(rec.abilities) ? rec.abilities.length : 0,
            skills: Array.isArray(rec.skills) ? rec.skills.length : 0,
            managed: managed.has(key),
            issues: validateEnemy(rec, { key, officialIds: officialEnemies }),
          });
        }
      }
      return sendJson(res, 200, { enemies, vocab: ENEMY_VOCAB(), officialEnemies: [...officialEnemies].sort() });
    }

    // derive + validate a monster WITHOUT writing: the form's live feedback
    if (p === '/api/enemies/preview' && method === 'POST') {
      const { spec } = await readBody(req);
      const derived = deriveEnemy(spec);
      if (!derived.ok) return sendJson(res, 200, { ok: false, errors: derived.errors, warnings: [] });
      const issues = validateEnemy(derived.enemy, { key: derived.enemy.key, officialIds: officialEnemies });
      return sendJson(res, 200, {
        ok: enemyErrors(issues).length === 0,
        errors: issues.filter((i) => i.severity === 'error'),
        warnings: [...derived.warnings, ...issues.filter((i) => i.severity === 'warning').map((i) => i.message)],
        record: derived.enemy,
      });
    }

    if (p.startsWith('/api/packs/') && p.endsWith('/enemies') && method === 'POST') {
      const packId = p.slice('/api/packs/'.length, -'/enemies'.length);
      if (!PACK_ID_RE.test(packId)) throw Object.assign(new Error('bad pack id'), { status: 400 });
      const { spec } = await readBody(req);
      const ids = enemyKeyOf(spec && spec.id);
      if (!ids) throw Object.assign(new Error('spec.id must be a slug (letters, digits, _ - . :)'), { status: 400 });
      const derived = deriveEnemy(spec);
      if (!derived.ok) return sendJson(res, 400, { error: 'the monster spec is invalid', errors: derived.errors });
      const blocking = enemyErrors(validateEnemy(derived.enemy, { key: derived.enemy.key, officialIds: officialEnemies }));
      if (blocking.length) return sendJson(res, 400, { error: 'the monster did not validate', errors: blocking });

      const packDir = path.join(root, packId);
      const manifestPath = path.join(packDir, 'pack.json');
      const existingManifest = readJson(manifestPath, null);
      const content = new Set(Array.isArray(existingManifest?.content) ? existingManifest.content : []);
      content.add('enemies');
      await writeJson(manifestPath, existingManifest
        ? { ...existingManifest, content: [...content].sort() }
        : { id: packId, name: spec.name || packId, version: '0.1.0', author: authorFor(packDir, forgeAuthor), license: null, description: null, gameVersion: '0.1.3', content: [...content], overrides: [] });
      const specPath = path.join(packDir, ENEMY_SPEC_DIR, `${ids.slug}.json`);
      const previousSpec = readJson(specPath, null);
      await writeJson(specPath, withForgeMeta(spec, { author: authorFor(packDir, forgeAuthor), packId, now: new Date().toISOString(), previous: previousSpec }));
      const regen = regenerateEnemies(packDir, officialEnemies);
      if (regen.errors.length) {
        return sendJson(res, 400, { error: 'another monster in this pack no longer derives — fix it before saving', errors: regen.errors });
      }
      await writeJson(path.join(packDir, 'enemies.json'), regen.records);
      return sendJson(res, 200, { ok: true, key: derived.enemy.key, generated: regen.generated, warnings: derived.warnings });
    }

    if (p.startsWith('/api/packs/') && p.includes('/enemies/') && method === 'DELETE') {
      const rest = p.slice('/api/packs/'.length);
      const cut = rest.indexOf('/enemies/');
      const packId = rest.slice(0, cut);
      const key = decodeURIComponent(rest.slice(cut + '/enemies/'.length));
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(key)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = enemyKeyOf(key);
      const specPath = path.join(root, packId, ENEMY_SPEC_DIR, `${ids.slug}.json`);
      if (fs.existsSync(specPath)) await fsp.rm(specPath);
      const regen = regenerateEnemies(path.join(root, packId), officialEnemies, [key]);
      await writeJson(path.join(root, packId, 'enemies.json'), regen.records);
      return sendJson(res, 200, { ok: true, removed: key, generated: regen.generated, errors: regen.errors });
    }

    // the stored SPEC the form edits (the source of truth), plus the generated record for reference
    if (p.startsWith('/api/enemies/') && method === 'GET') {
      const rest = p.slice('/api/enemies/'.length).split('/');
      if (rest.length !== 2) throw Object.assign(new Error('not found'), { status: 404 });
      const [packId, key] = rest;
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(key)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = enemyKeyOf(key);
      const packDir = path.join(root, packId);
      return sendJson(res, 200, {
        spec: ids ? readJson(path.join(packDir, ENEMY_SPEC_DIR, `${ids.slug}.json`), null) : null,
        record: (readJson(path.join(packDir, 'enemies.json'), {}) || {})[key] ?? null,
      });
    }

    // ---- 出怪 (waves): the timeline's data and its save path ----------------------------------------
    if (p === '/api/waves' && method === 'GET') {
      const waves = [];
      for (const packId of fs.existsSync(root) ? fs.readdirSync(root).sort() : []) {
        if (!PACK_ID_RE.test(packId) || !fs.existsSync(path.join(root, packId, 'pack.json'))) continue;
        const packDir = path.join(root, packId);
        const managed = new Set(packWaveSpecs(packDir).map((s) => {
          const ids = s && s.id ? waveIdOf(s.id) : null;
          return ids ? ids.id : null;
        }).filter(Boolean));
        const records = readJson(path.join(packDir, 'waves.json'), {}) || {};
        for (const [id, rec] of Object.entries(records)) {
          waves.push({
            pack: packId, id, kind: rec.kind ?? null, solo: rec.solo === true,
            routes: Array.isArray(rec.routes) ? rec.routes.length : 0,
            spawns: Array.isArray(rec.spawns) ? rec.spawns.length : 0,
            totalCount: rec.totalCount ?? null, slotCounts: rec.slotCounts ?? {},
            summary: waveSummaryLine(rec),
            modeRounds: Array.isArray(rec.usedBy) ? rec.usedBy.map((u) => `${u.modeId}#${u.round}`) : [],
            managed: managed.has(id),
            issues: validateWave(rec, { id, officialIds: officialWaves, knownEnemyKeys: knownEnemyKeysFor(root, dataDir) }),
          });
        }
      }
      return sendJson(res, 200, {
        waves,
        vocab: { kinds: [...WAVE_KINDS], slots: [...SPAWN_SLOTS], spawnFields: [...SPAWN_FIELDS], roundsPerMode: ROUNDS_PER_MODE },
        officialWaves: [...officialWaves].sort(),
        modes: inScopeModes(dataDir),
        // every spawnable enemy (official + the packs' own), so the timeline can offer a picker instead of a text field
        enemies: [...knownEnemyKeysFor(root, dataDir)].sort(),
        stages: stageChoices(root, dataDir),
      });
    }

    // derive + validate a wave WITHOUT writing: the timeline's live feedback
    if (p === '/api/waves/preview' && method === 'POST') {
      const { spec } = await readBody(req);
      const derived = deriveWave(spec);
      if (!derived.ok) return sendJson(res, 200, { ok: false, errors: derived.errors, warnings: [] });
      const issues = validateWave(derived.wave, { id: derived.wave.id, officialIds: officialWaves, knownEnemyKeys: knownEnemyKeysFor(root, dataDir) });
      return sendJson(res, 200, {
        ok: waveErrors(issues).length === 0,
        errors: issues.filter((i) => i.severity === 'error'),
        warnings: [...derived.warnings, ...issues.filter((i) => i.severity === 'warning').map((i) => i.message)],
        record: derived.wave,
      });
    }

    if (p.startsWith('/api/packs/') && p.endsWith('/waves') && method === 'POST') {
      const packId = p.slice('/api/packs/'.length, -'/waves'.length);
      if (!PACK_ID_RE.test(packId)) throw Object.assign(new Error('bad pack id'), { status: 400 });
      const { spec } = await readBody(req);
      const ids = waveIdOf(spec && spec.id);
      if (!ids) throw Object.assign(new Error('spec.id must be a slug (letters, digits, _ - . :)'), { status: 400 });
      const derived = deriveWave(spec);
      if (!derived.ok) return sendJson(res, 400, { error: 'the wave spec is invalid', errors: derived.errors });
      const blocking = waveErrors(validateWave(derived.wave, { id: derived.wave.id, officialIds: officialWaves, knownEnemyKeys: knownEnemyKeysFor(root, dataDir) }));
      if (blocking.length) return sendJson(res, 400, { error: 'the wave did not validate', errors: blocking });

      const packDir = path.join(root, packId);
      const manifestPath = path.join(packDir, 'pack.json');
      const existingManifest = readJson(manifestPath, null);
      const content = new Set(Array.isArray(existingManifest?.content) ? existingManifest.content : []);
      content.add('waves');
      await writeJson(manifestPath, existingManifest
        ? { ...existingManifest, content: [...content].sort() }
        : { id: packId, name: spec.name || packId, version: '0.1.0', author: authorFor(packDir, forgeAuthor), license: null, description: null, gameVersion: '0.1.3', content: [...content], overrides: [] });
      const specPath = path.join(packDir, WAVE_SPEC_DIR, `${ids.slug}.json`);
      const previousSpec = readJson(specPath, null);
      await writeJson(specPath, withForgeMeta(spec, { author: authorFor(packDir, forgeAuthor), packId, now: new Date().toISOString(), previous: previousSpec }));
      const regen = regenerateWaves(packDir, officialWaves, knownEnemyKeysFor(root, dataDir));
      if (regen.errors.length) {
        return sendJson(res, 400, { error: 'another wave in this pack no longer derives — fix it before saving', errors: regen.errors });
      }
      await writeJson(path.join(packDir, 'waves.json'), regen.records);
      return sendJson(res, 200, { ok: true, id: derived.wave.id, generated: regen.generated, warnings: derived.warnings });
    }

    if (p.startsWith('/api/packs/') && p.includes('/waves/') && method === 'DELETE') {
      const rest = p.slice('/api/packs/'.length);
      const cut = rest.indexOf('/waves/');
      const packId = rest.slice(0, cut);
      const waveId = rest.slice(cut + '/waves/'.length);
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(waveId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = waveIdOf(waveId);
      const specPath = path.join(root, packId, WAVE_SPEC_DIR, `${ids.slug}.json`);
      if (fs.existsSync(specPath)) await fsp.rm(specPath);
      const regen = regenerateWaves(path.join(root, packId), officialWaves, knownEnemyKeysFor(root, dataDir), [waveId]);
      await writeJson(path.join(root, packId, 'waves.json'), regen.records);
      return sendJson(res, 200, { ok: true, removed: waveId, generated: regen.generated, errors: regen.errors });
    }

    // the stored SPEC the timeline edits (the source of truth), plus the generated record for reference
    if (p.startsWith('/api/waves/') && method === 'GET') {
      const rest = p.slice('/api/waves/'.length).split('/');
      if (rest.length !== 2) throw Object.assign(new Error('not found'), { status: 404 });
      const [packId, waveId] = rest;
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(waveId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = waveIdOf(waveId);
      const packDir = path.join(root, packId);
      return sendJson(res, 200, {
        spec: ids ? readJson(path.join(packDir, WAVE_SPEC_DIR, `${ids.slug}.json`), null) : null,
        record: (readJson(path.join(packDir, 'waves.json'), {}) || {})[waveId] ?? null,
      });
    }

    // ---- 装备 (items): the form's data and its save path --------------------------------------------
    if (p === '/api/items' && method === 'GET') {
      const items = [];
      for (const packId of fs.existsSync(root) ? fs.readdirSync(root).sort() : []) {
        if (!PACK_ID_RE.test(packId) || !fs.existsSync(path.join(root, packId, 'pack.json'))) continue;
        const packDir = path.join(root, packId);
        const managed = new Set(packItemSpecs(packDir).map((s) => {
          const ids = s && s.id ? itemIdsOf(s.id) : null;
          return ids ? ids.slug : null;
        }).filter(Boolean));
        const records = readJson(path.join(packDir, 'items.json'), {}) || {};
        for (const [id, rec] of Object.entries(records)) {
          const ids = itemIdsOf(id);
          items.push({
            pack: packId, id, name: rec.name ?? id, itemType: rec.itemType ?? null, category: rec.category ?? null,
            tier: rec.tier ?? null, price: rec.price ?? null, isGolden: rec.isGolden === true,
            mergeable: rec.mergeable === true, duration: rec.duration ?? null, trapId: rec.trapId ?? null,
            buffs: Array.isArray(rec.buffs) ? rec.buffs.length : 0, params: rec.params ?? {},
            summary: itemSummaryLine(rec),
            managed: ids ? managed.has(ids.slug) : false,
            issues: validateItem(rec, { id, officialIds: officialItems }),
          });
        }
      }
      return sendJson(res, 200, {
        items,
        vocab: {
          types: [...ITEM_TYPES], categories: [...ITEM_CATEGORIES], countTypes: [...COUNT_TYPES],
          durations: [...ITEM_DURATIONS], upgradeNums: [...UPGRADE_NUMS],
        },
        officialItems: [...officialItems].sort(),
        // the art an item can borrow, since a pack ships none
        icons: itemIconChoices(dataDir),
      });
    }

    // derive + validate an item WITHOUT writing: the form's live feedback
    if (p === '/api/items/preview' && method === 'POST') {
      const { spec } = await readBody(req);
      const derived = deriveItem(spec);
      if (!derived.ok) return sendJson(res, 200, { ok: false, errors: derived.errors, warnings: [] });
      const records = [derived.base, derived.golden].filter(Boolean);
      const issues = records.flatMap((rec) => validateItem(rec, { id: rec.id, officialIds: officialItems }));
      return sendJson(res, 200, {
        ok: itemErrors(issues).length === 0,
        errors: issues.filter((i) => i.severity === 'error'),
        warnings: [...derived.warnings, ...issues.filter((i) => i.severity === 'warning').map((i) => i.message)],
        record: derived.base,
        golden: derived.golden,
      });
    }

    if (p.startsWith('/api/packs/') && p.endsWith('/items') && method === 'POST') {
      const packId = p.slice('/api/packs/'.length, -'/items'.length);
      if (!PACK_ID_RE.test(packId)) throw Object.assign(new Error('bad pack id'), { status: 400 });
      const { spec } = await readBody(req);
      const ids = itemIdsOf(spec && spec.id);
      if (!ids) throw Object.assign(new Error('spec.id must be a slug (letters, digits, _ - . :)'), { status: 400 });
      const derived = deriveItem(spec);
      if (!derived.ok) return sendJson(res, 400, { error: 'the item spec is invalid', errors: derived.errors });
      const blocking = [derived.base, derived.golden].filter(Boolean)
        .flatMap((rec) => itemErrors(validateItem(rec, { id: rec.id, officialIds: officialItems })));
      if (blocking.length) return sendJson(res, 400, { error: 'the item did not validate', errors: blocking });

      const packDir = path.join(root, packId);
      const manifestPath = path.join(packDir, 'pack.json');
      const existingManifest = readJson(manifestPath, null);
      const content = new Set(Array.isArray(existingManifest?.content) ? existingManifest.content : []);
      content.add('items');
      await writeJson(manifestPath, existingManifest
        ? { ...existingManifest, content: [...content].sort() }
        : { id: packId, name: spec.name || packId, version: '0.1.0', author: authorFor(packDir, forgeAuthor), license: null, description: null, gameVersion: '0.1.3', content: [...content], overrides: [] });
      const specPath = path.join(packDir, ITEM_SPEC_DIR, `${ids.slug}.json`);
      const previousSpec = readJson(specPath, null);
      await writeJson(specPath, withForgeMeta(spec, { author: authorFor(packDir, forgeAuthor), packId, now: new Date().toISOString(), previous: previousSpec }));
      const regen = regenerateItems(packDir, officialItems);
      if (regen.errors.length) {
        return sendJson(res, 400, { error: 'another item in this pack no longer derives — fix it before saving', errors: regen.errors });
      }
      await writeJson(path.join(packDir, 'items.json'), regen.records);
      return sendJson(res, 200, { ok: true, id: derived.base.id, goldenId: derived.golden ? derived.golden.id : null, generated: regen.generated, warnings: derived.warnings });
    }

    // Deleting drops the WHOLE pair: a base whose golden twin survives would be a merge target pointing at a ghost.
    if (p.startsWith('/api/packs/') && p.includes('/items/') && method === 'DELETE') {
      const rest = p.slice('/api/packs/'.length);
      const cut = rest.indexOf('/items/');
      const packId = rest.slice(0, cut);
      const itemId = decodeURIComponent(rest.slice(cut + '/items/'.length));
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(itemId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = itemIdsOf(itemId);
      if (!ids) throw Object.assign(new Error('bad id'), { status: 400 });
      const specPath = path.join(root, packId, ITEM_SPEC_DIR, `${ids.slug}.json`);
      if (fs.existsSync(specPath)) await fsp.rm(specPath);
      const regen = regenerateItems(path.join(root, packId), officialItems, [ids.base, ids.golden]);
      await writeJson(path.join(root, packId, 'items.json'), regen.records);
      return sendJson(res, 200, { ok: true, removed: [ids.base, ids.golden], generated: regen.generated, errors: regen.errors });
    }

    // the stored SPEC the form edits (the source of truth), plus the generated pair for reference
    if (p.startsWith('/api/items/') && method === 'GET') {
      const rest = p.slice('/api/items/'.length).split('/');
      if (rest.length !== 2) throw Object.assign(new Error('not found'), { status: 404 });
      const [packId, itemId] = rest;
      if (!PACK_ID_RE.test(packId) || !/^[A-Za-z0-9_\-.:]{1,64}$/.test(itemId)) throw Object.assign(new Error('bad id'), { status: 400 });
      const ids = itemIdsOf(itemId);
      const packDir = path.join(root, packId);
      const records = readJson(path.join(packDir, 'items.json'), {}) || {};
      return sendJson(res, 200, {
        spec: ids ? readJson(path.join(packDir, ITEM_SPEC_DIR, `${ids.slug}.json`), null) : null,
        record: records[itemId] ?? (ids ? records[ids.base] ?? null : null),
        golden: ids ? records[ids.golden] ?? null : null,
      });
    }

    // ---- 3D 预览的只读素材通路 ----------------------------------------------------------------------
    //
    // The map editor can show a map in the game's OWN 3D renderer (public/js/render/board3d). That is the whole point:
    // the preview is the game's code over the map's data, so it cannot drift from what players will see — the same
    // reason the path tables come from server/sim/grid.js instead of being re-implemented here.
    //
    // Three read-only mounts, all inside this repo and all localhost-only (the editor binds 127.0.0.1 by default):
    //   /client/**        the client modules the 3D stack imports (relative imports resolve inside this tree)
    //   /vendor/**        the vendored three.js build (tools/vendor.mjs)
    //   /assets/local/**  the board art the local-client manifest points at
    // plus /data/local-assets.json itself. Nothing is writable, nothing is listed, and `..`/dot-segments are refused.
    // When the art is absent the probe fails and the editor stays on the 2D canvas — the game client's own fallback.
    if (method === 'GET' || method === 'HEAD') {
      const previewMounts = [
        { prefix: '/client/', root: path.join(REPO_ROOT, 'public'), only: CLIENT_PREVIEW_TYPES },
        { prefix: '/vendor/', root: path.join(REPO_ROOT, 'public', 'vendor'), only: CLIENT_PREVIEW_TYPES },
        { prefix: '/assets/', root: path.join(REPO_ROOT, 'public', 'assets'), only: ART_TYPES },
      ];
      const mount = previewMounts.find((m) => p.startsWith(m.prefix));
      if (mount) {
        const segments = p.slice(mount.prefix.length).split('/').filter((s) => s.length > 0);
        const ext = segments.length ? path.extname(segments[segments.length - 1]).toLowerCase() : '';
        const bad = !segments.length || segments.some((s) => s === '..' || s === '.' || s.startsWith('.')) || !mount.only.has(ext);
        if (bad) throw Object.assign(new Error('not found'), { status: 404 });
        const abs = path.join(mount.root, ...segments);
        if (!abs.startsWith(mount.root + path.sep)) throw Object.assign(new Error('forbidden'), { status: 403 });
        let body;
        try {
          if (!fs.statSync(abs).isFile()) throw new Error('not a file');
          body = await fsp.readFile(abs);
        } catch { throw Object.assign(new Error('not found'), { status: 404 }); }
        res.writeHead(200, { 'Content-Type': ART_MIME.get(ext) ?? 'application/octet-stream', 'Content-Length': body.length, 'Cache-Control': 'no-cache' });
        res.end(method === 'HEAD' ? undefined : body);
        return;
      }
      // the local-art manifest itself; its `path` fields are absolute `/assets/local/...` URLs, served by the mount above
      if (p === '/data/local-assets.json') {
        let body;
        try { body = await fsp.readFile(path.join(DATA_DIR, 'local-assets.json')); } catch { throw Object.assign(new Error('not found'), { status: 404 }); }
        res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': body.length, 'Cache-Control': 'no-cache' });
        res.end(method === 'HEAD' ? undefined : body);
        return;
      }
    }

    // ---- the editor's own UI (never the game's) -----------------------------------------------------
    if (method !== 'GET') throw Object.assign(new Error('method not allowed'), { status: 405 });
    const rel = p === '/' ? 'index.html' : p.replace(/^\/+/, '');
    const abs = path.join(UI_DIR, rel);
    if (!abs.startsWith(UI_DIR + path.sep) && abs !== UI_DIR) throw Object.assign(new Error('forbidden'), { status: 403 });
    if (!fs.existsSync(abs) || !fs.statSync(abs).isFile()) throw Object.assign(new Error('not found'), { status: 404 });
    const body = await fsp.readFile(abs);
    res.writeHead(200, { 'Content-Type': MIME[path.extname(abs).toLowerCase()] ?? 'application/octet-stream', 'Content-Length': body.length, 'Cache-Control': 'no-store' });
    res.end(body);
  }

  const port = opts.port ?? 0;
  const host = opts.host ?? '127.0.0.1';
  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, resolve);
  });
  const actual = server.address().port;
  return {
    port: actual,
    host,
    url: `http://${host === '0.0.0.0' ? 'localhost' : host}:${actual}`,
    server,
    close: () => new Promise((resolve) => { server.close(() => resolve()); server.closeAllConnections?.(); }),
  };
}

export { formatIssues };
